version = 1
SPDX-PackageName = "ocm-sbom"
SPDX-PackageSupplier = "Olison Sturm <kontakt@example.com>"
SPDX-PackageDownloadLocation = "https://github.com/olisonsturm/ocm-sbom"

[[annotations]]
path = "docs/thesis/Sturm_Olison_Luk_Bogomil_WWIBE222_Bachelorarbeit.pdf"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Olison Sturm"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "docs"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Olison Sturm"
SPDX-License-Identifier = "Apache-2.0"
